%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'firstOrderDynamics_splines';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('firstOrderDynamics_splines.log');
M_.exo_names = 'aggregateTFPShock';
M_.exo_names_tex = 'aggregateTFPShock';
M_.exo_names_long = 'aggregateTFPShock';
M_.endo_names = 'coefficient_1_1';
M_.endo_names_tex = 'coefficient\_1\_1';
M_.endo_names_long = 'coefficient_1_1';
M_.endo_names = char(M_.endo_names, 'coefficient_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_1');
M_.endo_names = char(M_.endo_names, 'coefficient_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_2');
M_.endo_names = char(M_.endo_names, 'coefficient_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_2');
M_.endo_names = char(M_.endo_names, 'coefficient_1_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_3');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_3');
M_.endo_names = char(M_.endo_names, 'coefficient_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_3');
M_.endo_names = char(M_.endo_names, 'coefficient_1_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_4');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_4');
M_.endo_names = char(M_.endo_names, 'coefficient_2_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_4');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_4');
M_.endo_names = char(M_.endo_names, 'coefficient_1_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_5');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_5');
M_.endo_names = char(M_.endo_names, 'coefficient_2_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_5');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_5');
M_.endo_names = char(M_.endo_names, 'coefficient_1_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_6');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_6');
M_.endo_names = char(M_.endo_names, 'coefficient_2_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_6');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_6');
M_.endo_names = char(M_.endo_names, 'coefficient_1_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_7');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_7');
M_.endo_names = char(M_.endo_names, 'coefficient_2_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_7');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_7');
M_.endo_names = char(M_.endo_names, 'coefficient_1_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_8');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_8');
M_.endo_names = char(M_.endo_names, 'coefficient_2_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_8');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_8');
M_.endo_names = char(M_.endo_names, 'coefficient_1_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_9');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_9');
M_.endo_names = char(M_.endo_names, 'coefficient_2_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_9');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_9');
M_.endo_names = char(M_.endo_names, 'coefficient_1_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_10');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_10');
M_.endo_names = char(M_.endo_names, 'coefficient_2_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_10');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_10');
M_.endo_names = char(M_.endo_names, 'coefficient_1_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_11');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_11');
M_.endo_names = char(M_.endo_names, 'coefficient_2_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_11');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_11');
M_.endo_names = char(M_.endo_names, 'coefficient_1_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_12');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_12');
M_.endo_names = char(M_.endo_names, 'coefficient_2_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_12');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_12');
M_.endo_names = char(M_.endo_names, 'coefficient_1_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_13');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_13');
M_.endo_names = char(M_.endo_names, 'coefficient_2_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_13');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_13');
M_.endo_names = char(M_.endo_names, 'coefficient_1_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_14');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_14');
M_.endo_names = char(M_.endo_names, 'coefficient_2_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_14');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_14');
M_.endo_names = char(M_.endo_names, 'coefficient_1_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_15');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_15');
M_.endo_names = char(M_.endo_names, 'coefficient_2_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_15');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_15');
M_.endo_names = char(M_.endo_names, 'coefficient_1_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_16');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_16');
M_.endo_names = char(M_.endo_names, 'coefficient_2_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_16');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_16');
M_.endo_names = char(M_.endo_names, 'coefficient_1_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_17');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_17');
M_.endo_names = char(M_.endo_names, 'coefficient_2_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_17');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_17');
M_.endo_names = char(M_.endo_names, 'coefficient_1_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_18');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_18');
M_.endo_names = char(M_.endo_names, 'coefficient_2_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_18');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_18');
M_.endo_names = char(M_.endo_names, 'coefficient_1_19');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_19');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_19');
M_.endo_names = char(M_.endo_names, 'coefficient_2_19');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_19');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_19');
M_.endo_names = char(M_.endo_names, 'coefficient_1_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_20');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_20');
M_.endo_names = char(M_.endo_names, 'coefficient_2_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_20');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_20');
M_.endo_names = char(M_.endo_names, 'coefficient_1_21');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_21');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_21');
M_.endo_names = char(M_.endo_names, 'coefficient_2_21');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_21');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_21');
M_.endo_names = char(M_.endo_names, 'coefficient_1_22');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_22');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_22');
M_.endo_names = char(M_.endo_names, 'coefficient_2_22');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_22');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_22');
M_.endo_names = char(M_.endo_names, 'coefficient_1_23');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_23');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_23');
M_.endo_names = char(M_.endo_names, 'coefficient_2_23');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_23');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_23');
M_.endo_names = char(M_.endo_names, 'coefficient_1_24');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_24');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_24');
M_.endo_names = char(M_.endo_names, 'coefficient_2_24');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_24');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_24');
M_.endo_names = char(M_.endo_names, 'coefficient_1_25');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_1\_25');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_1_25');
M_.endo_names = char(M_.endo_names, 'coefficient_2_25');
M_.endo_names_tex = char(M_.endo_names_tex, 'coefficient\_2\_25');
M_.endo_names_long = char(M_.endo_names_long, 'coefficient_2_25');
M_.endo_names = char(M_.endo_names, 'moment_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'moment_1_1');
M_.endo_names = char(M_.endo_names, 'moment_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'moment_2_1');
M_.endo_names = char(M_.endo_names, 'moment_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'moment_1_2');
M_.endo_names = char(M_.endo_names, 'moment_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'moment_2_2');
M_.endo_names = char(M_.endo_names, 'moment_1_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_1\_3');
M_.endo_names_long = char(M_.endo_names_long, 'moment_1_3');
M_.endo_names = char(M_.endo_names, 'moment_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'moment\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'moment_2_3');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_1_1');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_2_1');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_1_2');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_2_2');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_1_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_1\_3');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_1_3');
M_.endo_names = char(M_.endo_names, 'measureCoefficient_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'measureCoefficient\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'measureCoefficient_2_3');
M_.endo_names = char(M_.endo_names, 'mHat_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'mHat\_1');
M_.endo_names_long = char(M_.endo_names_long, 'mHat_1');
M_.endo_names = char(M_.endo_names, 'mHat_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'mHat\_2');
M_.endo_names_long = char(M_.endo_names_long, 'mHat_2');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'aggregateTFP');
M_.endo_names_tex = char(M_.endo_names_tex, 'aggregateTFP');
M_.endo_names_long = char(M_.endo_names_long, 'aggregateTFP');
M_.endo_names = char(M_.endo_names, 'logAggregateOutput');
M_.endo_names_tex = char(M_.endo_names_tex, 'logAggregateOutput');
M_.endo_names_long = char(M_.endo_names_long, 'logAggregateOutput');
M_.endo_names = char(M_.endo_names, 'logAggregateInvestment');
M_.endo_names_tex = char(M_.endo_names_tex, 'logAggregateInvestment');
M_.endo_names_long = char(M_.endo_names_long, 'logAggregateInvestment');
M_.endo_names = char(M_.endo_names, 'logAggregateConsumption');
M_.endo_names_tex = char(M_.endo_names_tex, 'logAggregateConsumption');
M_.endo_names_long = char(M_.endo_names_long, 'logAggregateConsumption');
M_.endo_names = char(M_.endo_names, 'logWage');
M_.endo_names_tex = char(M_.endo_names_tex, 'logWage');
M_.endo_names_long = char(M_.endo_names_long, 'logWage');
M_.param_names = 'bbeta';
M_.param_names_tex = 'bbeta';
M_.param_names_long = 'bbeta';
M_.param_names = char(M_.param_names, 'ssigma');
M_.param_names_tex = char(M_.param_names_tex, 'ssigma');
M_.param_names_long = char(M_.param_names_long, 'ssigma');
M_.param_names = char(M_.param_names, 'aaBar');
M_.param_names_tex = char(M_.param_names_tex, 'aaBar');
M_.param_names_long = char(M_.param_names_long, 'aaBar');
M_.param_names = char(M_.param_names, 'aalpha');
M_.param_names_tex = char(M_.param_names_tex, 'aalpha');
M_.param_names_long = char(M_.param_names_long, 'aalpha');
M_.param_names = char(M_.param_names, 'ddelta');
M_.param_names_tex = char(M_.param_names_tex, 'ddelta');
M_.param_names_long = char(M_.param_names_long, 'ddelta');
M_.param_names = char(M_.param_names, 'aggEmployment');
M_.param_names_tex = char(M_.param_names_tex, 'aggEmployment');
M_.param_names_long = char(M_.param_names_long, 'aggEmployment');
M_.param_names = char(M_.param_names, 'mmu');
M_.param_names_tex = char(M_.param_names_tex, 'mmu');
M_.param_names_long = char(M_.param_names_long, 'mmu');
M_.param_names = char(M_.param_names, 'ttau');
M_.param_names_tex = char(M_.param_names_tex, 'ttau');
M_.param_names_long = char(M_.param_names_long, 'ttau');
M_.param_names = char(M_.param_names, 'rrhoTFP');
M_.param_names_tex = char(M_.param_names_tex, 'rrhoTFP');
M_.param_names_long = char(M_.param_names_long, 'rrhoTFP');
M_.param_names = char(M_.param_names, 'ssigmaTFP');
M_.param_names_tex = char(M_.param_names_tex, 'ssigmaTFP');
M_.param_names_long = char(M_.param_names_long, 'ssigmaTFP');
M_.param_names = char(M_.param_names, 'epsilonTransition_1_1');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonTransition\_1\_1');
M_.param_names_long = char(M_.param_names_long, 'epsilonTransition_1_1');
M_.param_names = char(M_.param_names, 'epsilonTransition_1_2');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonTransition\_1\_2');
M_.param_names_long = char(M_.param_names_long, 'epsilonTransition_1_2');
M_.param_names = char(M_.param_names, 'epsilonTransition_2_1');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonTransition\_2\_1');
M_.param_names_long = char(M_.param_names_long, 'epsilonTransition_2_1');
M_.param_names = char(M_.param_names, 'epsilonTransition_2_2');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonTransition\_2\_2');
M_.param_names_long = char(M_.param_names_long, 'epsilonTransition_2_2');
M_.param_names = char(M_.param_names, 'epsilonMass_1');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonMass\_1');
M_.param_names_long = char(M_.param_names_long, 'epsilonMass_1');
M_.param_names = char(M_.param_names, 'epsilonMass_2');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonMass\_2');
M_.param_names_long = char(M_.param_names_long, 'epsilonMass_2');
M_.param_names = char(M_.param_names, 'nEpsilon');
M_.param_names_tex = char(M_.param_names_tex, 'nEpsilon');
M_.param_names_long = char(M_.param_names_long, 'nEpsilon');
M_.param_names = char(M_.param_names, 'nAssets');
M_.param_names_tex = char(M_.param_names_tex, 'nAssets');
M_.param_names_long = char(M_.param_names_long, 'nAssets');
M_.param_names = char(M_.param_names, 'nState');
M_.param_names_tex = char(M_.param_names_tex, 'nState');
M_.param_names_long = char(M_.param_names_long, 'nState');
M_.param_names = char(M_.param_names, 'assetsMin');
M_.param_names_tex = char(M_.param_names_tex, 'assetsMin');
M_.param_names_long = char(M_.param_names_long, 'assetsMin');
M_.param_names = char(M_.param_names, 'assetsMax');
M_.param_names_tex = char(M_.param_names_tex, 'assetsMax');
M_.param_names_long = char(M_.param_names_long, 'assetsMax');
M_.param_names = char(M_.param_names, 'nAssetsFine');
M_.param_names_tex = char(M_.param_names_tex, 'nAssetsFine');
M_.param_names_long = char(M_.param_names_long, 'nAssetsFine');
M_.param_names = char(M_.param_names, 'nStateFine');
M_.param_names_tex = char(M_.param_names_tex, 'nStateFine');
M_.param_names_long = char(M_.param_names_long, 'nStateFine');
M_.param_names = char(M_.param_names, 'nAssetsQuadrature');
M_.param_names_tex = char(M_.param_names_tex, 'nAssetsQuadrature');
M_.param_names_long = char(M_.param_names_long, 'nAssetsQuadrature');
M_.param_names = char(M_.param_names, 'nStateQuadrature');
M_.param_names_tex = char(M_.param_names_tex, 'nStateQuadrature');
M_.param_names_long = char(M_.param_names_long, 'nStateQuadrature');
M_.param_names = char(M_.param_names, 'nMeasure');
M_.param_names_tex = char(M_.param_names_tex, 'nMeasure');
M_.param_names_long = char(M_.param_names_long, 'nMeasure');
M_.param_names = char(M_.param_names, 'nMeasureCoefficients');
M_.param_names_tex = char(M_.param_names_tex, 'nMeasureCoefficients');
M_.param_names_long = char(M_.param_names_long, 'nMeasureCoefficients');
M_.param_names = char(M_.param_names, 'kRepSS');
M_.param_names_tex = char(M_.param_names_tex, 'kRepSS');
M_.param_names_long = char(M_.param_names_long, 'kRepSS');
M_.param_names = char(M_.param_names, 'maxIterations');
M_.param_names_tex = char(M_.param_names_tex, 'maxIterations');
M_.param_names_long = char(M_.param_names_long, 'maxIterations');
M_.param_names = char(M_.param_names, 'tolerance');
M_.param_names_tex = char(M_.param_names_tex, 'tolerance');
M_.param_names_long = char(M_.param_names_long, 'tolerance');
M_.param_names = char(M_.param_names, 'dampening');
M_.param_names_tex = char(M_.param_names_tex, 'dampening');
M_.param_names_long = char(M_.param_names_long, 'dampening');
M_.param_names = char(M_.param_names, 'epsilonGrid_1');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonGrid\_1');
M_.param_names_long = char(M_.param_names_long, 'epsilonGrid_1');
M_.param_names = char(M_.param_names, 'epsilonGrid_2');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonGrid\_2');
M_.param_names_long = char(M_.param_names_long, 'epsilonGrid_2');
M_.param_names = char(M_.param_names, 'assetsGrid_1');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_1');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_1');
M_.param_names = char(M_.param_names, 'assetsGrid_2');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_2');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_2');
M_.param_names = char(M_.param_names, 'assetsGrid_3');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_3');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_3');
M_.param_names = char(M_.param_names, 'assetsGrid_4');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_4');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_4');
M_.param_names = char(M_.param_names, 'assetsGrid_5');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_5');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_5');
M_.param_names = char(M_.param_names, 'assetsGrid_6');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_6');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_6');
M_.param_names = char(M_.param_names, 'assetsGrid_7');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_7');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_7');
M_.param_names = char(M_.param_names, 'assetsGrid_8');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_8');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_8');
M_.param_names = char(M_.param_names, 'assetsGrid_9');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_9');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_9');
M_.param_names = char(M_.param_names, 'assetsGrid_10');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_10');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_10');
M_.param_names = char(M_.param_names, 'assetsGrid_11');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_11');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_11');
M_.param_names = char(M_.param_names, 'assetsGrid_12');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_12');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_12');
M_.param_names = char(M_.param_names, 'assetsGrid_13');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_13');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_13');
M_.param_names = char(M_.param_names, 'assetsGrid_14');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_14');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_14');
M_.param_names = char(M_.param_names, 'assetsGrid_15');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_15');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_15');
M_.param_names = char(M_.param_names, 'assetsGrid_16');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_16');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_16');
M_.param_names = char(M_.param_names, 'assetsGrid_17');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_17');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_17');
M_.param_names = char(M_.param_names, 'assetsGrid_18');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_18');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_18');
M_.param_names = char(M_.param_names, 'assetsGrid_19');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_19');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_19');
M_.param_names = char(M_.param_names, 'assetsGrid_20');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_20');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_20');
M_.param_names = char(M_.param_names, 'assetsGrid_21');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_21');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_21');
M_.param_names = char(M_.param_names, 'assetsGrid_22');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_22');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_22');
M_.param_names = char(M_.param_names, 'assetsGrid_23');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_23');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_23');
M_.param_names = char(M_.param_names, 'assetsGrid_24');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_24');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_24');
M_.param_names = char(M_.param_names, 'assetsGrid_25');
M_.param_names_tex = char(M_.param_names_tex, 'assetsGrid\_25');
M_.param_names_long = char(M_.param_names_long, 'assetsGrid_25');
M_.param_names = char(M_.param_names, 'quadratureGrid_1');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_1');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_1');
M_.param_names = char(M_.param_names, 'quadratureWeights_1');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_1');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_1');
M_.param_names = char(M_.param_names, 'quadratureGrid_2');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_2');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_2');
M_.param_names = char(M_.param_names, 'quadratureWeights_2');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_2');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_2');
M_.param_names = char(M_.param_names, 'quadratureGrid_3');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_3');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_3');
M_.param_names = char(M_.param_names, 'quadratureWeights_3');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_3');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_3');
M_.param_names = char(M_.param_names, 'quadratureGrid_4');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_4');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_4');
M_.param_names = char(M_.param_names, 'quadratureWeights_4');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_4');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_4');
M_.param_names = char(M_.param_names, 'quadratureGrid_5');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_5');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_5');
M_.param_names = char(M_.param_names, 'quadratureWeights_5');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_5');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_5');
M_.param_names = char(M_.param_names, 'quadratureGrid_6');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_6');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_6');
M_.param_names = char(M_.param_names, 'quadratureWeights_6');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_6');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_6');
M_.param_names = char(M_.param_names, 'quadratureGrid_7');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_7');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_7');
M_.param_names = char(M_.param_names, 'quadratureWeights_7');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_7');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_7');
M_.param_names = char(M_.param_names, 'quadratureGrid_8');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureGrid\_8');
M_.param_names_long = char(M_.param_names_long, 'quadratureGrid_8');
M_.param_names = char(M_.param_names, 'quadratureWeights_8');
M_.param_names_tex = char(M_.param_names_tex, 'quadratureWeights\_8');
M_.param_names_long = char(M_.param_names_long, 'quadratureWeights_8');
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 71;
M_.param_nbr = 74;
M_.orig_endo_nbr = 71;
M_.aux_vars = [];
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('firstOrderDynamics_splines_static');
erase_compiled_function('firstOrderDynamics_splines_dynamic');
M_.lead_lag_incidence = [
 0 10 81;
 0 11 82;
 0 12 83;
 0 13 84;
 0 14 85;
 0 15 86;
 0 16 87;
 0 17 88;
 0 18 89;
 0 19 90;
 0 20 91;
 0 21 92;
 0 22 93;
 0 23 94;
 0 24 95;
 0 25 96;
 0 26 97;
 0 27 98;
 0 28 99;
 0 29 100;
 0 30 101;
 0 31 102;
 0 32 103;
 0 33 104;
 0 34 105;
 0 35 106;
 0 36 107;
 0 37 108;
 0 38 109;
 0 39 110;
 0 40 111;
 0 41 112;
 0 42 113;
 0 43 114;
 0 44 115;
 0 45 116;
 0 46 117;
 0 47 118;
 0 48 119;
 0 49 120;
 0 50 121;
 0 51 122;
 0 52 123;
 0 53 124;
 0 54 125;
 0 55 126;
 0 56 127;
 0 57 128;
 0 58 129;
 0 59 130;
 1 60 0;
 2 61 0;
 3 62 0;
 4 63 0;
 5 64 0;
 6 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 7 72 0;
 8 73 0;
 0 74 131;
 0 75 132;
 9 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;]';
M_.nstatic = 10;
M_.nfwrd   = 52;
M_.npred   = 9;
M_.nboth   = 0;
M_.nsfwrd   = 52;
M_.nspred   = 9;
M_.ndynamic   = 61;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(71, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(74, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 3235;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
economicParameters = load('economicParameters');
approximationParameters = load('approximationParameters');
grids = load('grids');
for iParam = 1 : 10
parameterName = deblank(M_.param_names(iParam,:));
if isfield(economicParameters,parameterName)
M_.params(iParam) = eval(['economicParameters.' parameterName]);
end
end
for iEpsilon = 1 : 2
for iEpsilonPrime = 1 : 2
M_.params(10 + 2 * (iEpsilon - 1) + iEpsilonPrime) = ...
			economicParameters.mEpsilonTransition(iEpsilon,iEpsilonPrime);
end
end
M_.params( 15 ) = 1-M_.params(6);
epsilonMass_1 = M_.params( 15 );
M_.params( 16 ) = M_.params(6);
epsilonMass_2 = M_.params( 16 );
for iParam = 1 : 15
parameterName = deblank(M_.param_names(10 + 6 + iParam,:));
if isfield(approximationParameters,parameterName)
M_.params(10 + 6 + iParam) = eval(['approximationParameters.' parameterName]);
end
end
M_.params( 32 ) = 0;
epsilonGrid_1 = M_.params( 32 );
M_.params( 33 ) = 1;
epsilonGrid_2 = M_.params( 33 );
for iAssets = 1 : 25
M_.params(33 + iAssets) = grids.vAssetsGrid(iAssets);
end
for iAssets = 1 : 8
M_.params(58 + 2 * (iAssets - 1) + 1) = grids.vAssetsGridQuadrature(iAssets);
M_.params(58 + 2 * (iAssets - 1) + 2) = grids.vQuadratureWeights(iAssets);
end
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
options_.steadystate.nocheck = 1;
steady;
options_.hp_filter = 100;
options_.irf = 40;
options_.order = 1;
var_list_=[];
var_list_ = 'aggregateTFP';
var_list_ = char(var_list_, 'logAggregateOutput');
var_list_ = char(var_list_, 'logAggregateConsumption');
var_list_ = char(var_list_, 'logAggregateInvestment');
var_list_ = char(var_list_, 'logWage');
var_list_ = char(var_list_, 'r');
info = stoch_simul(var_list_);
save('firstOrderDynamics_splines_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('firstOrderDynamics_splines_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('firstOrderDynamics_splines_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('firstOrderDynamics_splines_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('firstOrderDynamics_splines_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
